### ISSUE TITLE
separate workflow into components

### ISSUE THREAD

**Issue by bvreede** [esciencecenter-digital-skills/training-infrastructure#15]
At the moment, files get created and uploaded in the same loop as channels are created. It would be useful to separate the different elements of the workflow, so that errors in one do not cause problems for other aspects, and elements can be tested (i.e. it can be verified that they have been executed correctly).

**Comment by liekelotte** [comment]
for 7, 8, and 12: creating two functions: create_data_file and upload_docs. the latter will have a flexible argument indicating which docs (i.e. upload_docs(slug, comms = TRUE, debriefing = TRUE, planning = TRUE, data = TRUE))
