### ISSUE TITLE
improve github actions - deprecated workflow

### ISSUE THREAD

**Issue by liekelotte** [esciencecenter-digital-skills/training-infrastructure#28]
for details: 

https://github.com/esciencecenter-digital-skills/training-infrastructure/actions/runs/3312624352

**Comment by liekelotte** [comment]
Actually, it failed because my tests failed. That's now updated. There is a lot of info about deprecated workflows though

**Comment by bvreede** [comment]
I think we can close this; our GA workflows run! 🎉
