### ISSUE TITLE
Use versioning

### ISSUE THREAD

**Issue by svenvanderburg** [esciencecenter-digital-skills/training-infrastructure#43]
I find that I have often trouble to install the latest version of this package. I am no R expert, but I think that if you would bump the version once in a while: https://github.com/esciencecenter-digital-skills/training-infrastructure/blob/14a726e04d9e36131deb666abe7bc17212fd9850/DESCRIPTION#L3
This would make RStudio recognize that the package is outdated and reinstall the package if I tell it to.

**Comment by bvreede** [comment]
Yes! New release forthcoming after #39 :)
