### ISSUE TITLE
protect main branch

### ISSUE THREAD

**Issue by bvreede** [esciencecenter-digital-skills/training-infrastructure#58]
I just accidentally pushed to `main` 😱
Can we set up branch protection @liekelotte? I don't have admin rights so I can't do this myself, but lmk if you want help.

🙏 

PS I fixed it, but it was a very painful twenty minutes.

**Comment by mkuzak** [comment]
Hi barbara, which rule do you want to set?
![Screenshot 2023-02-09 at 09 53 22](https://user-images.githubusercontent.com/208443/217763622-42f0998a-f7d6-4538-b70d-17b1a99ac938.png)

**Comment by bvreede** [comment]
<img width="804" alt="Screenshot 2023-02-09 at 13 11 07" src="https://user-images.githubusercontent.com/5747405/217809461-ae4c9f16-cf04-472c-9852-bbb612452880.png">

I'd want this one :) — thanks @mkuzak!

**Comment by mkuzak** [comment]
Apologies it took so long. I think it is set now.

**Comment by bvreede** [comment]
Yes it is! Dziękuję 🙏🏼 ;)
