### ISSUE TITLE
add information about cancellation

### ISSUE THREAD

**Issue by Sachavb** [esciencecenter-digital-skills/training-infrastructure#59]
We have a lot of no-shows and people are not cancelling their registration. We should add information emphasising the importance of cancellation on the Eventbrite pages and workshop website pages. I suggest to add the following text: 

If you won’t be able to attend, please cancel your registration (by following instructions here [https:/[www.eventbrite.com/support/articles/en_US/How_To/how-to-cancel-your-free-registration](http://www.eventbrite.com/support/articles/en_US/How_To/how-to-cancel-your-free-registration)> [3]) so that we can offer your seat to someone on the waiting list.

**Comment by FenneRiemslagh** [comment]
Closed as adressed by "add info about cancellation to eventbrite page #16"
